const $ = (id) => document.getElementById(id);

export function getDomRefs() {
  return {
    appShell: document.querySelector(".app-shell"),
    drawer: $("drawer"),
    backdrop: $("backdrop"),
    messages: $("messages"),
    chatList: $("chatList"),
    chatListTitle: $("chatListTitle"),
    chatSearchWrap: $("chatSearchWrap"),
    chatSearchInput: $("chatSearchInput"),
    clearChatSearchBtn: $("clearChatSearchBtn"),
    newChatBtn: $("newChatBtn"),
    archivesBtn: $("archivesBtn"),
    drawerCompactBtn: $("drawerCompactBtn"),
    sidebarRail: $("sidebarRail"),
    modelList: $("modelList"),
    modelSheet: $("modelSheet"),
    settingsSheet: $("settingsSheet"),
    settingsBtn: $("settingsBtn"),
    currentModelLabel: $("currentModelLabel"),
    messageInput: $("messageInput"),
    baseUrlInput: $("baseUrlInput"),
    modeHint: $("modeHint"),
    runtimeStatus: $("runtimeStatus"),
    mockModeBtn: $("mockModeBtn"),
    runtimeModeBtn: $("runtimeModeBtn"),
    streamModeToggle: $("streamModeToggle"),
    ttsToggle: $("ttsToggle"),
    statusDot: document.querySelector(".status-dot"),
    themeToggleBtn: $("themeToggleBtn"),
    micBtn: $("micBtn"),
    composer: document.querySelector(".composer"),
    replyBanner: $("replyBanner"),
    replyBannerText: $("replyBannerText"),
    clearReplyBtn: $("clearReplyBtn"),
    closeSettingsBtn: $("closeSettingsBtn"),

    menuBtn: $("menuBtn"),
    closeDrawerBtn: $("closeDrawerBtn"),
    modelPickerBtn: $("modelPickerBtn"),
    closeModelSheetBtn: $("closeModelSheetBtn"),
    saveBaseUrlBtn: $("saveBaseUrlBtn"),
    detectModelsBtn: $("detectModelsBtn"),
    connectLocalLlamaBtn: $("connectLocalLlamaBtn"),
    sendBtn: $("sendBtn"),
    plusBtn: $("plusBtn"),
  };
}
